blank_issues_enabled: false
contact_links:
  - name: â“ Ask a question
    url: https://github.com/huhouhua/go-nuget/discussions/new?category=q-a
    about:  Ask and discuss questions with other go-nuget community members

  - name: ğŸ““ Reference
    url: https://pkg.go.dev/mod/github.com/huhouhua/go-nuget
    about: Check the Go code reference